server:
  port: ${PORT:8080}

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.KafkaAutoConfiguration
  profiles:
    active: ${ENV}
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:producer
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  cloud:
    stream:
      default:
        contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        bolsa-exchange:
          destination: bolsa